definitions:
  model.User:
    properties:
      avatar:
        type: string
      created_at:
        type: integer
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      salt:
        type: string
      updated_at:
        type: integer
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /users/:id:
    get:
      consumes:
      - application/json
      description: 依据用户的id，查询用户的信息
      parameters:
      - description: 用户id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: 查询用户信息
swagger: "2.0"
